id = "laravel-official"
name = "Laravel (Official)"
description = "Official Laravel LSP integration."
version = "0.7.0"
schema_version = 1
authors = ["Laravel"]
repository = "https://github.com/laravel/zed-extension"

[language_servers.laravel]
name = "Laravel LSP"
languages = ["PHP", "Blade"]
language_ids = { PHP = "php", Blade = "blade" }
